# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# Enable block entities light source.
	block_entities = true
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				glow_item_frame = false
				player = true
				rabbit = true
				bat = true
				skeleton = true
				glow_squid = true
				squid = true
				creeper = true
				drowned = true
				zombie = true
				spider = true
				witch = true
				enderman = true
				iron_golem = true
				villager = true
				item = true
				chest_minecart = true
				hoglin = true
				piglin = true
				zombified_piglin = true
				strider = true
				salmon = true

